"""CSAF 2.0 advisory generation for EURA compliance scan results.

Generates Common Security Advisory Framework (CSAF) 2.0 JSON documents
from EURA scan data — vulnerability reports, rule evaluation results, and
dependency analysis.  CSAF advisories enable automated consumption of
security advisories by vulnerability scanners and patch management tools.

Specification: https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html
PRD Reference:  Section 3.8.1 — CRA Mandatory Artifacts (CSAF export).
"""
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.core.logger import logger

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CSAF_VERSION = "2.0"
TOOL_NAME = "EURA"
TOOL_VERSION = "2.0"
TOOL_URI = "https://github.com/eura-compliance/eura"

# CSAF document categories
CSAF_CATEGORY_VEX = "csaf_vex"
CSAF_CATEGORY_ADVISORY = "csaf_security_advisory"

# CVSS severity thresholds (approximate from score ranges)
_SEVERITY_CVSS_RANGES: Dict[str, Dict[str, float]] = {
    "CRITICAL": {"base_score": 9.5},
    "HIGH": {"base_score": 7.5},
    "MEDIUM": {"base_score": 5.0},
    "LOW": {"base_score": 2.5},
}

# Map from EURA severity to CSAF severity text
_SEVERITY_TEXT: Dict[str, str] = {
    "CRITICAL": "Critical",
    "HIGH": "High",
    "MEDIUM": "Medium",
    "LOW": "Low",
    "UNKNOWN": "Unknown",
}

# Map from EURA severity to CSAF product_status key
_STATUS_KEYS: Dict[str, str] = {
    "affected": "known_affected",
    "not_affected": "known_not_affected",
    "fixed": "fixed",
    "under_investigation": "under_investigation",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_product_id(
    package_name: str,
    version: str = "",
    ecosystem: str = "",
) -> str:
    """Build a CSAF-compatible product identifier."""
    eco = ecosystem.lower() if ecosystem else "generic"
    base = f"pkg:{eco}/{package_name}"
    if version:
        base += f"@{version}"
    return base


def _make_tracking(
    doc_id: str,
    now: str,
    revision_number: str = "1",
) -> Dict[str, Any]:
    """Build the CSAF tracking block."""
    return {
        "current_release_date": now,
        "id": doc_id,
        "initial_release_date": now,
        "revision_history": [
            {
                "date": now,
                "number": revision_number,
                "summary": "Initial automated advisory generated by EURA.",
            }
        ],
        "status": "final",
        "version": revision_number,
        "generator": {
            "engine": {
                "name": TOOL_NAME,
                "version": TOOL_VERSION,
            }
        },
    }


def _make_publisher(
    vendor_name: str = "EURA Compliance Scanner",
    namespace: str = "https://eura.dev",
) -> Dict[str, Any]:
    """Build the CSAF publisher block."""
    return {
        "category": "tool",
        "name": vendor_name,
        "namespace": namespace,
    }


def _make_product_tree(
    products: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build CSAF product_tree from dependency/package data."""
    branches: List[Dict[str, Any]] = []
    full_product_names: List[Dict[str, Any]] = []

    # Group packages by ecosystem
    ecosystems: Dict[str, List[Dict[str, Any]]] = {}
    for prod in products:
        eco = prod.get("ecosystem", prod.get("type", "generic")).lower()
        if eco not in ecosystems:
            ecosystems[eco] = []
        ecosystems[eco].append(prod)

    for eco, pkgs in ecosystems.items():
        eco_branches: List[Dict[str, Any]] = []
        for pkg in pkgs:
            name = pkg.get("name", "unknown")
            version = pkg.get("version", "")
            product_id = _make_product_id(name, version, eco)

            pkg_branch: Dict[str, Any] = {
                "category": "product_name",
                "name": f"{name}@{version}" if version else name,
                "product": {
                    "name": f"{name} {version}".strip(),
                    "product_id": product_id,
                },
            }
            eco_branches.append(pkg_branch)
            full_product_names.append({
                "name": f"{name} {version}".strip(),
                "product_id": product_id,
            })

        branches.append({
            "category": "product_family",
            "name": eco,
            "branches": eco_branches,
        })

    tree: Dict[str, Any] = {}
    if branches:
        tree["branches"] = branches
    if full_product_names:
        tree["full_product_names"] = full_product_names

    return tree


def _make_vulnerability(
    vuln: Dict[str, Any],
) -> Dict[str, Any]:
    """Convert a single EURA vulnerability dict to a CSAF vulnerability."""
    vuln_id = vuln.get("vuln_id", vuln.get("id", ""))
    summary = vuln.get("summary", "")
    severity = vuln.get("severity", "UNKNOWN").upper()
    package = vuln.get("affected_package", "unknown")
    version = vuln.get("affected_version", "")
    fixed_version = vuln.get("fixed_version", "")
    ecosystem = vuln.get("ecosystem", vuln.get("type", ""))
    references = vuln.get("references", [])

    product_id = _make_product_id(package, version, ecosystem)

    csaf_vuln: Dict[str, Any] = {}

    # CVE identifier
    if vuln_id.startswith("CVE-"):
        csaf_vuln["cve"] = vuln_id
    csaf_vuln["title"] = vuln_id

    # Notes
    notes: List[Dict[str, str]] = []
    if summary:
        notes.append({"category": "summary", "text": summary})
    notes.append({
        "category": "general",
        "text": f"Detected by EURA compliance scanner in {package}.",
    })
    if notes:
        csaf_vuln["notes"] = notes

    # Product status
    product_status: Dict[str, List[str]] = {}

    # Determine status
    vex_status = vuln.get("vex_status", "").lower()
    if vex_status in _STATUS_KEYS:
        status_key = _STATUS_KEYS[vex_status]
    elif fixed_version:
        status_key = "known_affected"  # fix available, still on old version
    else:
        status_key = "known_affected"

    product_status[status_key] = [product_id]

    # If there's a fixed version, add the fixed product too
    if fixed_version:
        fixed_product_id = _make_product_id(package, fixed_version, ecosystem)
        product_status.setdefault("fixed", [])
        product_status["fixed"].append(fixed_product_id)

    csaf_vuln["product_status"] = product_status

    # Remediations
    remediations: List[Dict[str, Any]] = []
    if fixed_version:
        remediations.append({
            "category": "vendor_fix",
            "details": f"Upgrade {package} to version {fixed_version} or later.",
            "product_ids": [product_id],
        })
    action = vuln.get("action_statement", "")
    if action and not fixed_version:
        remediations.append({
            "category": "workaround",
            "details": action,
            "product_ids": [product_id],
        })
    if remediations:
        csaf_vuln["remediations"] = remediations

    # Scores (CVSS v3.1 approximate)
    if severity in _SEVERITY_CVSS_RANGES:
        score_value = _SEVERITY_CVSS_RANGES[severity]["base_score"]
        csaf_vuln["scores"] = [
            {
                "products": [product_id],
                "cvss_v3": {
                    "version": "3.1",
                    "baseScore": score_value,
                    "baseSeverity": _SEVERITY_TEXT.get(severity, "Unknown").upper(),
                    "vectorString": f"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                },
            }
        ]

    # References
    if references:
        csaf_refs: List[Dict[str, str]] = []
        for ref in references[:10]:  # limit to 10
            if isinstance(ref, str):
                csaf_refs.append({
                    "url": ref,
                    "summary": f"Reference for {vuln_id}",
                })
            elif isinstance(ref, dict):
                csaf_refs.append({
                    "url": ref.get("url", ""),
                    "summary": ref.get("summary", f"Reference for {vuln_id}"),
                })
        if csaf_refs:
            csaf_vuln["references"] = csaf_refs

    return csaf_vuln


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_csaf(
    vulnerabilities: List[Dict[str, Any]],
    *,
    repo_name: Optional[str] = None,
    commit_sha: Optional[str] = None,
    scan_id: Optional[str] = None,
    title: Optional[str] = None,
    publisher_name: str = "EURA Compliance Scanner",
    publisher_namespace: str = "https://eura.dev",
    document_id: Optional[str] = None,
    category: str = CSAF_CATEGORY_VEX,
) -> Dict[str, Any]:
    """Generate a CSAF 2.0 JSON advisory from vulnerability data.

    Args:
        vulnerabilities: List of vulnerability dicts, each containing at
            minimum ``vuln_id`` (or ``id``), ``affected_package``,
            ``severity``.  Optional fields: ``affected_version``,
            ``fixed_version``, ``summary``, ``ecosystem``, ``references``,
            ``vex_status``, ``action_statement``.
        repo_name: Repository identifier (e.g. ``owner/repo``).
        commit_sha: Git commit hash.
        scan_id: EURA scan UUID.
        title: Advisory title.  Auto-generated if omitted.
        publisher_name: Name for the CSAF publisher block.
        publisher_namespace: Namespace URI for the publisher.
        document_id: Explicit CSAF tracking ID.  Auto-generated if omitted.
        category: CSAF document category (``csaf_vex`` or
            ``csaf_security_advisory``).

    Returns:
        CSAF 2.0 document as a Python dict (JSON-serializable).
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    doc_id = document_id or f"EURA-CSAF-{uuid.uuid4().hex[:12]}"

    if not title:
        repo_label = repo_name or "project"
        title = f"EURA Security Advisory for {repo_label}"

    # ------------------------------------------------------------------
    # Build product tree from vulnerability packages
    # ------------------------------------------------------------------
    products: List[Dict[str, Any]] = []
    seen_products: set = set()

    for vuln in vulnerabilities:
        package = vuln.get("affected_package", "unknown")
        version = vuln.get("affected_version", "")
        ecosystem = vuln.get("ecosystem", vuln.get("type", ""))
        key = (package, version, ecosystem)
        if key not in seen_products:
            seen_products.add(key)
            products.append({
                "name": package,
                "version": version,
                "ecosystem": ecosystem,
            })
        # Also add fixed versions
        fixed = vuln.get("fixed_version", "")
        if fixed:
            fix_key = (package, fixed, ecosystem)
            if fix_key not in seen_products:
                seen_products.add(fix_key)
                products.append({
                    "name": package,
                    "version": fixed,
                    "ecosystem": ecosystem,
                })

    product_tree = _make_product_tree(products)

    # ------------------------------------------------------------------
    # Build vulnerabilities
    # ------------------------------------------------------------------
    csaf_vulns: List[Dict[str, Any]] = []
    for vuln in vulnerabilities:
        csaf_vulns.append(_make_vulnerability(vuln))

    # ------------------------------------------------------------------
    # Assemble CSAF document
    # ------------------------------------------------------------------
    csaf: Dict[str, Any] = {
        "document": {
            "category": category,
            "csaf_version": CSAF_VERSION,
            "title": title,
            "publisher": _make_publisher(publisher_name, publisher_namespace),
            "tracking": _make_tracking(doc_id, now),
            "distribution": {
                "tlp": {
                    "label": "WHITE",
                }
            },
            "lang": "en",
            "notes": [
                {
                    "category": "summary",
                    "text": (
                        f"Automated security advisory generated by {TOOL_NAME} v{TOOL_VERSION}. "
                        f"Contains {len(vulnerabilities)} vulnerability finding(s)."
                    ),
                }
            ],
        },
    }

    if product_tree:
        csaf["product_tree"] = product_tree

    if csaf_vulns:
        csaf["vulnerabilities"] = csaf_vulns

    # Add EURA metadata as document-level notes
    if repo_name or commit_sha or scan_id:
        meta_parts: List[str] = []
        if repo_name:
            meta_parts.append(f"Repository: {repo_name}")
        if commit_sha:
            meta_parts.append(f"Commit: {commit_sha}")
        if scan_id:
            meta_parts.append(f"Scan ID: {scan_id}")
        csaf["document"]["notes"].append({
            "category": "other",
            "title": "EURA Scan Metadata",
            "text": "; ".join(meta_parts),
        })

    vuln_count = len(csaf_vulns)
    product_count = len(products)
    logger.debug(
        "Generated CSAF 2.0 document: %d vulnerabilities, %d products",
        vuln_count, product_count,
    )

    return csaf
